# -*- coding: utf-8 -*-
"""Processing_image_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11wn7_Fn2dQuNGP0Kpp6asPyQ4g8HID4M
"""



"""TOPICS

1) READING AN IMAGE FILE AND CONVERTING IT TO NUMPY ARRAY

2) RESIZING IMAGE

3)RGB TO GARYSCALE CONVERSION
"""

!wget "https://up.yimg.com/ib/th?id=OIP.BK8STvfoGAkPFIe0cTCMxAHaFj&pid=Api&rs=1&c=1&qlt=95&w=142&h=106"

import matplotlib.image as mpimg
import matplotlib.pyplot as plt

img=mpimg.imread("/content/th?id=OIP.BK8STvfoGAkPFIe0cTCMxAHaFj&pid=Api&rs=1&c=1&qlt=95&w=142&h=106")

type(img)

print(img.shape)

print(img)

# displaying image from numpy array

img_plot=plt.imshow(img)
plt.show()

# resizing image using pillow

from PIL import Image

img=Image.open("/content/th?id=OIP.BK8STvfoGAkPFIe0cTCMxAHaFj&pid=Api&rs=1&c=1&qlt=95&w=142&h=106")
img_resized=img.resize((200,200))

print(img_resized)

img_resized.save("/content/th?id=OIP.BK8STvfoGAkPFIe0cTCMxAHaFj&pid=Api&rs=1&c=1&qlt=95&w=142&h=106.jpg")

img_rs=mpimg.imread('/content/th?id=OIP.BK8STvfoGAkPFIe0cTCMxAHaFj&pid=Api&rs=1&c=1&qlt=95&w=142&h=106.jpg')

img_plot=plt.imshow(img_rs)
plt.show()

# convert rgb into grayscale

import cv2

img=cv2.imread("/content/th?id=OIP.BK8STvfoGAkPFIe0cTCMxAHaFj&pid=Api&rs=1&c=1&qlt=95&w=142&h=106.jpg")

type(img)

img.shape

gray_scale_image=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

print(gray_scale_image)

type(gray_scale_image)

gray_scale_image.shape

#cv2.imshow() not allow in colab

from google.colab.patches import cv2_imshow
cv2_imshow(gray_scale_image)

